# ╔══════════════════════════════════════════════╗
# ║           ZRestoreBack Config                ║
# ║           Plugin version: 1.0                ║
# ║         https://t.me/Zoobastiks              ║
# ╚══════════════════════════════════════════════╝
#
# ОБЩАЯ ИНФОРМАЦИЯ:
# ZRestoreBack позволяет игрокам возвращаться на место смерти и восстанавливать
# потерянные предметы за валюту сервера. Все сообщения, цены и миры можно настроить.
#
# КОМАНДЫ ПЛАГИНА:
# /dp или /deathpoints - показать список точек смерти
# /dp list - показать список точек смерти
# /dp tp <номер> - телепортироваться на место смерти
# /dp items <номер> - восстановить предметы с места смерти
# /dp <номер> - телепортироваться на место смерти по номеру
# /dp help - показать справку по командам
# /dp reload - перезагрузить конфигурацию (требуется право zrestoreback.admin)
# /dp save - ручное сохранение данных о смертях (требуется право zrestoreback.save)
#
# ПРАВА ПЛАГИНА:
# zrestoreback.use - основные функции плагина (по умолчанию у всех)
# zrestoreback.admin - администраторские функции (перезагрузка, доступ к чужим точкам)
# zrestoreback.reload - перезагрузка конфигурации (включено в zrestoreback.admin)
# zrestoreback.save - разрешение на ручное сохранение данных (по умолчанию: op)
#
# НАСТРОИВАЕМЫЕ МИРЫ, В КОТОРЫХ РАБОТАЕТ ПЛАГИН
worlds:
  # Список миров, в которых плагин работает (точки смерти сохраняются)
  # Оставьте пустым и добавьте "*" для активации во всех мирах
  enabled:
    - "world"
    - "lobby_nether"
    - "lobby_the_end"
    - "lobby_kattersstructures_deep_blue"
  
  # Список миров, в которых плагин НЕ работает (имеет приоритет над enabled)
  # Полезно, когда enabled содержит "*", но вы хотите исключить некоторые миры
  disabled:
    - "lobby"
    - "oneblock_world"

# ЭКОНОМИЧЕСКИЕ НАСТРОЙКИ (требуется Vault и плагин экономики)
economy:
  # Цена за телепортацию на место смерти
  # Можно установить 0 для бесплатной телепортации
  teleport_cost: 100.0
  
  # Цена за восстановление предметов
  # Можно установить 0 для бесплатного восстановления предметов
  items_return_cost: 250.0

# НАСТРОЙКИ СООБЩЕНИЙ
# Вы можете использовать цветовые коды, HEX цвета, градиенты и другие форматы
messages:
  # Заголовок сообщения со списком точек смерти
  header: "<gradient:#FF0000:#FFFF00>===== Точки смерти =====</gradient>"
  
  # Сообщение о точке смерти (для каждой точки)
  # Плейсхолдеры: %world% - мир, %x% %y% %z% - координаты, %index% - номер точки
  death_point: "<#00AAFF>Смерть #%index%: <white>%world% <gray>(%x%, %y%, %z%)</gray></white>"
  
  # Нижний колонтитул сообщения
  footer: "<gradient:#FFFF00:#FF0000>=====================</gradient>"
  
  # Текст кнопки телепортации (отображается в чате)
  teleport_button: "[Телепорт]"
  
  # Текст кнопки восстановления предметов (отображается в чате)
  items_button: "[Вещи]"
  
  # Сообщение об успешной телепортации
  # Плейсхолдер: %cost% - стоимость телепортации
  teleport_success: "<gradient:#00FF00:#00AAFF>Вы были телепортированы на место смерти за %cost% монет.</gradient>"
  
  # Сообщение о недостатке средств для телепортации
  # Плейсхолдер: %cost% - стоимость телепортации
  teleport_fail: "&cУ вас недостаточно средств для телепортации.\n&cТребуется: %cost% монет."
  
  # Сообщение об успешном восстановлении предметов
  # Плейсхолдер: %cost% - стоимость восстановления предметов
  items_return_success: "&aВаши вещи были возвращены за %cost% монет."
  
  # Сообщение о недостатке средств для восстановления предметов
  # Плейсхолдер: %cost% - стоимость восстановления предметов
  items_return_fail: "<#FF0000>У вас недостаточно средств для возврата вещей.\n<#FF5555>Требуется: %cost% монет."
  
  # Сообщение об отсутствии точек смерти
  no_death_points: "&cУ вас нет сохраненных точек смерти."
  
  # Сообщение о неверном индексе точки смерти
  invalid_death_point: "<red>Указанная точка смерти не существует.</red>"

# НАСТРОЙКИ ЗВУКОВ
sounds:
  # Звук при смерти
  death:
    # Включить/выключить звук
    enabled: true
    # Название звука (в формате minecraft:category.name)
    sound: "entity.wither.death"
  
  # Звук при телепортации на место смерти
  teleport:
    enabled: true
    sound: "entity.enderman.teleport"
  
  # Звук при восстановлении предметов
  items_return:
    enabled: true
    sound: "entity.player.levelup"

# НАСТРОЙКИ КОМАНД, ВЫПОЛНЯЕМЫХ ПРИ СМЕРТИ
commands:
  # Включить/выключить выполнение команд при смерти
  execute_on_death: false
  
  # Список команд, выполняемых при смерти игрока
  # Плейсхолдеры: %player% - имя игрока, %world% - мир, %x% %y% %z% - координаты
  on_death:
    - "say %player% умер в мире %world% на координатах %x% %y% %z%"
    # - "broadcast %player% умер на координатах %x% %y% %z% в мире %world%"
    # - "execute at %player% run particle minecraft:explosion ~ ~ ~ 1 1 1 0.1 10"

# ОГРАНИЧЕНИЯ И ЛИМИТЫ
settings:
  # Миры, в которых плагин активен
  enabled_worlds:
    - "world"
    - "world_nether"
    - "world_the_end"
  
  # Миры, в которых плагин выключен
  disabled_worlds:
    - "lobby"
    - "oneblock_world"
  
  # Максимальное количество сохраняемых точек смерти для каждого игрока
  # Когда лимит достигнут, самые старые точки удаляются
  max_deaths_stored: 5
  
  # Максимальное количество точек смерти, показываемых в сообщении
  # Самые новые точки будут показаны первыми
  max_deaths_shown: 5
  
  # Настройки автосохранения данных
  # Интервал автоматического сохранения (в минутах)
  auto_save_interval: 10
  
  # Показывать сообщения о сохранении данных в консоли
  show_save_messages: true

# ФОРМАТИРОВАНИЕ СООБЩЕНИЙ:
# 1. Переносы строк: Используйте \n для добавления новой строки
#    Пример: "Первая строка\nВторая строка"
#
# 2. Градиенты и MiniMessage форматирование:
#    <gradient:#FF0000:#A6EB0F>Текст в градиенте</gradient>
#    <#FF0000>Текст HEX цветом
#    &4Красный текст, §1Синий текст
#
# 3. Форматы текста:
#    &l или <bold> - жирный текст
#    &o или <italic> - курсив
#    &n или <underlined> - подчеркнутый текст
#    &k или <obfuscated> - скрытый текст
#    &m или <strikethrough> - зачеркнутый текст
#    &r или <reset> - сброс форматирования

# ЗВУКИ:
# Используйте формат "entity.название.действие", например:
# entity.wither.death - звук смерти иссушителя
# entity.enderman.teleport - звук телепорта эндермена
# entity.player.levelup - звук повышения уровня игрока
# block.note_block.bell - звук колокола нотного блока
# Полный список звуков: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html 